version: '3.9'
services:
    nango-rabbit:
        image: rabbitmq:3-management
        container_name: nango-rabbit
        ports:
            - '5672:5672'
            - '8082:15672'

    nango-db:
        image: postgres
        container_name: nango-db
        restart: always
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '5432:5432'

    nango-db-admin:
        image: adminer
        container_name: nango-db-admin
        restart: always
        ports:
            - '8080:8080'

    nango-server:
        image: nangohq/server
        container_name: nango-server
        restart: always
        ports:
            - '3003:3003'
        depends_on:
            - nango-rabbit
            - nango-db

    nango-worker:
        image: nangohq/worker
        container_name: nango-worker
        restart: always
        ports:
            - '3004:3004'
        depends_on:
            - nango-rabbit
            - nango-db
