version: '3.9'

services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: nango-rabbit
        ports:
            - '5672:5672'
            - '8082:15672'

    server:
        #build: packages/server
        image: nangohq/server
        container_name: nango-server
        volumes:
            - type: bind
              source: ${NANGO_INTEGRATIONS_DIR}
              target: /usr/nango-server/src/nango-integrations
        links:
            - rabbitmq
        depends_on:
            - rabbitmq
