version: '3.9'
services:
    nango-server:
        image: nangohq/server
        container_name: nango-server
        restart: always
        env_file:
            - .env
        ports:
            - '3003:3003'
        depends_on:
            - temporal
        networks:
            - nango

    nango-worker:
        image: nangohq/worker
        container_name: nango-worker
        restart: always
        env_file:
            - .env
        ports:
            - '3004:3004'
        depends_on:
            - temporal
        networks:
            - nango

    temporal:
        container_name: temporal
        env_file:
            - .env
        image: temporalio/auto-setup:1.18.4
        ports:
            - 7233:7233
        labels:
            kompose.volume.type: configMap
        networks:
            - nango

networks:
    nango:
