# Expected to be used like this:
# docker-compose -f docker-compose.yaml -f docker-compose.debug.yaml up
version: '3.9'
services:
    nango-server:
        environment:
            - TELEMETRY=FALSE
    nango-worker:
        environment:
            - TELEMETRY=FALSE
    temporal-ui:
        image: temporalio/ui:latest
        depends_on:
            - temporal
        container_name: temporal-ui
        environment:
            - TEMPORAL_ADDRESS=temporal:7233
            - TEMPORAL_CORS_ORIGINS=http://localhost:3000
        ports:
            - 8011:8080
        networks:
            - nango
